export enum QueryKeys {
  useAuthLogin = 'useAuthLogin',
  useAuthResetPassword = 'useAuthResetPassword',
  useAuthForgotPassword = 'useAuthForgotPassword',
  useGetAccountData = 'useGetAccountData',
  useUpdateAccountData = 'useUpdateAccountData',
  useGetVerified = 'useGetVerified',
  useAuthLogout = 'useAuthLogout',

  useGetUsers = 'useGetUsers',
  useUpdateUser = 'useUpdateUser',
  useDeleteUser = 'useDeleteUser',
  useResetPassword = 'useResetPassword',

  useGetMachines = 'useGetMachines',
  useGetMachinesPerGeography = 'useGetMachinesPerGeography',

  useGetImpressions = 'useGetImpressions',
  useGetImpressionsPerRange = 'useGetImpressionsPerRange',
  useGetImpressionsPerGeography = 'useGetImpressionsPerGeography',
  useGetImpressionsSchedule = 'useGetImpressionsSchedule',
  useScheduleImpressionsExport = 'useScheduleImpressionsExport',
  useExportImpressions = 'useExportImpressions',
  useDeleteImpressionsSchedule = 'useDeleteImpressionsSchedule',
  useGetAvgImpressions = 'useGetAvgImpressions',
  useGetAdvertsPlayout = 'useGetAdvertsPlayout',
  useGetAvgExposure = 'useGetAvgExposure',
  useGetMonthOnMonthSummary = 'useGetMonthOnMonthSummary',
  useGetExposurePerRange = 'useGetExposurePerRange',
  useGetImpressionsByVenue = 'useGetImpressionsByVenue',

  useGetGeographies = 'useGetGeographies',

  useGetSales = 'useGetSales',
  useGetAvgSales = 'useGetAvgSales',
  useGetAvgSalesPerRange = 'useGetAvgSalesPerRange',
  useGetQuantityByProduct = 'useGetQuantityByProduct',
  useGetQuantityPerRange = 'useGetQuantityPerRange',
  useGetQuantityPerProduct = 'useGetQuantityPerProduct',
  useGetQuantityPerProductOverTime = 'useGetQuantityPerProductOverTime',
  useGetSalesPerTimePeriod = 'useGetSalesPerTimePeriod',
  useGetUnitsSold = 'useGetUnitsSold',
  useGetQuantityPerGeography = 'useGetQuantityPerGeography',
  useGetConversionRate = 'useGetConversionRate',
  useGetFrequencyOfSales = 'useGetFrequencyOfSales',
  useGetSalesQuantityByVenue = 'useGetSalesQuantityByVenue',
  useExportSales = 'useExportSales',
  useScheduleSalesExport = 'useScheduleSalesExport',
  useGetSalesSchedule = 'useGetSalesSchedule',
  useGetSalesQuantityByCategory = 'useGetSalesQuantityByCategory',
  useDeleteSalesSchedule = 'useDeleteSalesSchedule',
  useGetAvgProductsPerGeography = 'useGetAvgProductsPerGeography',

  useGetProducts = 'useGetProducts',

  useGetActivityLog = 'useGetActivityLog',

  useGetVenue = 'useGetVenue',
}
